runtime: nodejs16

instance_class: F2

env_variables: 
  BUCKET_NAME: "to-do-list-angular"

handlers:
- url: /
  static_files: dist/to-do-list/index.html
  upload: dist/to-do-list/index.html

- url: /
  static_dir: dist/to-do-list